### ISSUE TITLE
Version 0.10.0 breaks relationship resolution for some documents

### ISSUE THREAD

**Issue by adsr303** [noplay/json-api-doc#12]
* JSON API doc version: 0.10.0
* Python version: 3.7.5
* Operating System: Windows
[brokenjsonapidoc.zip](https://github.com/noplay/json-api-doc/files/3887493/brokenjsonapidoc.zip)

### Description

I deserialized the attached document. Only the basic structure from `data` is available in the decoded document. Version 0.9.0 can resolve all relationships.

### What I Did

```python
import json
import json_api_doc
with open('brokenjsonapidoc.json') as f:
    doc = json_api_doc.deserialize(json.load(f))
print(doc)
```

**Comment by noplay** [comment]
Fixed in last release
