### ISSUE TITLE
serialize() should not convert an empty list to None

### ISSUE THREAD

**Issue by rogerrohrbach** [noplay/json-api-doc#16]
* JSON API doc version: 0.9.0
* Python version: 3.7.1
* Operating System: macOS 10.13.6

### Description

 `json_api_doc.serialize([])` returns `{'data': None}`.  I believe it ought to return `{'data': []}`, to support [primary data](https://jsonapi.org/format/#document-top-level) representing an empty resource collection.

If you agree, I'll submit a pull request.

**Comment by noplay** [comment]
Yes you are right

Le sam. 22 févr. 2020 à 02:05, Roger Rohrbach <notifications@github.com> a
écrit :

**Comment by rogerrohrbach** [comment]
I submitted PR #17.  The build is failing with dependency resolution issues for Python 3.4 (which appears to have been occurring since the beginning of the year). Maybe supporting that version is no longer worth it?

**Comment by rogerrohrbach** [comment]
Ah—sorry.  I didn't realize it was incumbent on me to close this.
